<?php

namespace Muglug\PackageVersions;

/**
 * This class is generated by muglug/package-versions-56, specifically by
 * @see \Muglug\PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    public static $VERSIONS = array (
  'gettext/gettext' => 'v4.8.2@e474f872f2c8636cf53fd283ec4ce1218f3d236a',
  'gettext/languages' => '2.6.0@38ea0482f649e0802e475f0ed19fa993bcb7a618',
  'paragonie/random_compat' => 'v2.0.18@0a58ef6e3146256cc3dc7cc393927bcc7d1b72db',
  'phpfastcache/riak-client' => '3.4.3@d771f75d16196006604a30bb15adc1c6a9b0fcc9',
  'phpmailer/phpmailer' => 'v6.1.7@2c2370ba3df7034f9eb7b8f387c97b52b2ba5ad0',
  'psr/container' => '1.0.0@b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
  'psr/log' => '1.1.3@0f73288fd15629204f9d42b7055f72dacbe811fc',
  'robrichards/xmlseclibs' => '3.1.0@8d8e56ca7914440a8c60caff1a865e7dff1d9a5a',
  'simplesamlphp/composer-module-installer' => 'v1.1.8@45161b5406f3e9c82459d0f9a5a1dba064953cfa',
  'simplesamlphp/saml2' => 'v3.4.5@acc47782592866423942dc30002c5220203ab466',
  'simplesamlphp/simplesamlphp-module-adfs' => 'v0.9.6@425e5ebbdd097c92fe5265a6b48d32a3095c7237',
  'simplesamlphp/simplesamlphp-module-authcrypt' => 'v0.9.2@2ad0f234b92ab0abe94e97fa3e1e04f9c743eb9d',
  'simplesamlphp/simplesamlphp-module-authfacebook' => 'v0.9.3@9152731e939ad4a49e0f06da5f0009ebde0d2b5c',
  'simplesamlphp/simplesamlphp-module-authorize' => 'v0.9.2@c2607a5252ee1256b50ce7795e35513b116998d4',
  'simplesamlphp/simplesamlphp-module-authtwitter' => 'v0.9.1@29a15e58061222632fea9eb2c807aef5e2c0d54a',
  'simplesamlphp/simplesamlphp-module-authwindowslive' => 'v0.9.1@f40aecec6c0adaedb6693309840c98cec783876e',
  'simplesamlphp/simplesamlphp-module-authx509' => 'v0.9.5@d4bae5d1c02f291d420607c14a157cef3bc36f5c',
  'simplesamlphp/simplesamlphp-module-authyubikey' => 'v0.9.1@8c27bfeb4981d2e6fa40a831e945f40c5a4ad3d2',
  'simplesamlphp/simplesamlphp-module-cas' => 'v0.9.1@63b72e4600550c507cdfc32fdd208ad59a64321e',
  'simplesamlphp/simplesamlphp-module-cdc' => 'v0.9.1@16a5bfac7299e04e5feb472af328e07598708166',
  'simplesamlphp/simplesamlphp-module-consent' => 'v0.9.6@2f84d15e96afb5a32b6d1cff93370f501ca7867d',
  'simplesamlphp/simplesamlphp-module-consentadmin' => 'v0.9.1@466e8d0d751f0080162d78e63ab2e125b24d17a1',
  'simplesamlphp/simplesamlphp-module-discopower' => 'v0.9.3@c892926e8186d0a2c638f7032dfc30540c1f92fb',
  'simplesamlphp/simplesamlphp-module-exampleattributeserver' => 'v1.0.0@63e0323e81c32bc3c9eaa01ea45194bb10153708',
  'simplesamlphp/simplesamlphp-module-expirycheck' => 'v0.9.3@59c59cdf87e2679257b46c07bb4c27666a11cc20',
  'simplesamlphp/simplesamlphp-module-ldap' => 'v0.9.9@27f0ef60482ff6a063dac5b7d59e8d3d407b52ac',
  'simplesamlphp/simplesamlphp-module-memcachemonitor' => 'v0.9.1@0e08e87707cd7b1fb91bbcf65cc454d8849571b0',
  'simplesamlphp/simplesamlphp-module-memcookie' => 'v1.2.2@39535304e8d464b7baa1e82cb441fa432947ff57',
  'simplesamlphp/simplesamlphp-module-metarefresh' => 'v0.9.6@e284306a7097297765b5b78a4e28f19f18d4e001',
  'simplesamlphp/simplesamlphp-module-negotiate' => 'v0.9.9@68c9a1a2b81c68978ba6cfe19f0a7527300768ba',
  'simplesamlphp/simplesamlphp-module-oauth' => 'v0.9.2@d14d7aca6e699ec12b3f4dd0128373faa1a2cc61',
  'simplesamlphp/simplesamlphp-module-preprodwarning' => 'v0.9.2@8e032de33a75eb44857dc06d886ad94ee3af4638',
  'simplesamlphp/simplesamlphp-module-radius' => 'v0.9.3@36bd0f39f9a13f7eb96ead97c97c3634aa1c3f2d',
  'simplesamlphp/simplesamlphp-module-riak' => 'v0.9.1@c1a9d9545cb4e05b9205b34624850bb777aca991',
  'simplesamlphp/simplesamlphp-module-sanitycheck' => 'v0.9.1@15d6664eae73a233c3c4c72fd8a5c2be72b6ed2a',
  'simplesamlphp/simplesamlphp-module-smartattributes' => 'v0.9.1@b45d3ecd916e359a9cae05f9ae9df09b5c42f4e6',
  'simplesamlphp/simplesamlphp-module-sqlauth' => 'v0.9.1@31bce8763ad97f4b4473e4ad4a5a96ddc136ef6b',
  'simplesamlphp/simplesamlphp-module-statistics' => 'v0.9.4@1bb1e46921d8dc84707bc9cd3c307c8abd723ac7',
  'simplesamlphp/twig-configurable-i18n' => 'v2.2@b036c134157ce40ed66da2fc9d01f63e3b1d3abd',
  'symfony/config' => 'v3.4.43@9e2aa97f0d51f114983666f5aa362426d53e004a',
  'symfony/debug' => 'v3.4.43@7ce874f4432d8b11cc45a80cc5130a6e2609728d',
  'symfony/dependency-injection' => 'v3.4.43@3a14abc01c36e81fc1c4c48b42c103b9dd892ed3',
  'symfony/event-dispatcher' => 'v3.4.43@14d978f8e8555f2de719c00eb65376be7d2e9081',
  'symfony/filesystem' => 'v3.4.43@0f625d0cb1e59c8c4ba61abb170125175218ff10',
  'symfony/http-foundation' => 'v3.4.43@5219dba1253aa07ed3ad82f73c08146fb3f517d0',
  'symfony/http-kernel' => 'v3.4.43@4a1c6b310806adce0f299411951d06747edf9e28',
  'symfony/polyfill-ctype' => 'v1.18.1@1c302646f6efc070cd46856e600e5e0684d6b454',
  'symfony/polyfill-mbstring' => 'v1.18.1@a6977d63bf9a0ad4c65cd352709e230876f9904a',
  'symfony/polyfill-php56' => 'v1.18.1@13df84e91cd168f247c2f2ec82cc0fa24901c011',
  'symfony/polyfill-php70' => 'v1.18.1@0dd93f2c578bdc9c72697eaa5f1dd25644e618d3',
  'symfony/polyfill-util' => 'v1.18.1@46b910c71e9828f8ec2aa7a0314de1130d9b295a',
  'symfony/routing' => 'v3.4.43@58381b7b815c1e3afaf60a534fbf769157fe5fe7',
  'symfony/yaml' => 'v3.4.43@e7fa05917ae931332a42d65b577ece4d497aad81',
  'twig/extensions' => 'v1.5.4@57873c8b0c1be51caa47df2cdb824490beb16202',
  'twig/twig' => 'v1.42.5@87b2ea9d8f6fd014d0621ca089bb1b3769ea3f8e',
  'webmozart/assert' => '1.5.0@88e6d84706d09a236046d686bbea96f07b3a34f4',
  'whitehat101/apr1-md5' => 'v1.0.0@8b261c9fc0481b4e9fa9d01c6ca70867b5d5e819',
  'composer/ca-bundle' => '1.2.8@8a7ecad675253e4654ea05505233285377405215',
  'composer/xdebug-handler' => '1.4.3@ebd27a9866ae8254e873866f795491f02418c5a5',
  'doctrine/instantiator' => '1.0.5@8e884e78f9f0eb1329e445619e04456e64d8051d',
  'guzzlehttp/guzzle' => '6.5.5@9d4290de1cfd701f38099ef7e183b64b4b7b0c5e',
  'guzzlehttp/promises' => 'v1.3.1@a59da6cf61d80060647ff4d3eb2c03a2bc694646',
  'guzzlehttp/psr7' => '1.6.1@239400de7a173fe9901b9ac7c06497751f00727a',
  'mikey179/vfsstream' => 'v1.6.8@231c73783ebb7dd9ec77916c10037eff5a2b6efe',
  'muglug/package-versions-56' => '1.2.4@a67bed26deaaf9269a348e53063bc8d4dcc60ffd',
  'myclabs/deep-copy' => '1.7.0@3b8a3a99ba1f6a3952ac2747d989303cbd6b7a3e',
  'nikic/php-parser' => 'v3.1.5@bb87e28e7d7b8d9a7fda231d37457c9210faf6ce',
  'openlss/lib-array2xml' => '0.5.1@c8b5998a342d7861f2e921403f44e0a2f3ef2be0',
  'php-coveralls/php-coveralls' => 'v2.2.0@3e6420fa666ef7bae5e750ddeac903153e193bae',
  'php-cs-fixer/diff' => 'v1.3.0@78bb099e9c16361126c86ce82ec4405ebab8e756',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '3.3.2@bf329f6c1aadea3299f08ee804682b7c45b326a2',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'phpspec/prophecy' => 'v1.10.3@451c3cd1418cf640de218914901e51b064abb093',
  'phpunit/php-code-coverage' => '4.0.8@ef7b2f56815df854e66ceaee8ebe9393ae36a40d',
  'phpunit/php-file-iterator' => '1.4.5@730b01bc3e867237eaac355e06a36b85dd93a8b4',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.9@3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
  'phpunit/php-token-stream' => '1.4.12@1ce90ba27c42e4e44e6d8458241466380b51fa16',
  'phpunit/phpunit' => '5.7.27@b7803aeca3ccb99ad0a506fa80b64cd6a56bbc0c',
  'phpunit/phpunit-mock-objects' => '3.4.4@a23b761686d50a560cc56233b9ecf49597cc9118',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'ralouphie/getallheaders' => '3.0.3@120b605dfeb996808c31b6477290a714d356e822',
  'sebastian/code-unit-reverse-lookup' => '1.0.1@4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
  'sebastian/comparator' => '1.2.4@2b7424b55f5047b47ac6e5ccb20b2aea4011d9be',
  'sebastian/diff' => '1.4.3@7f066a26a962dbe58ddea9f72a4e82874a3975a4',
  'sebastian/environment' => '2.0.0@5795ffe5dc5b02460c3e34222fee8cbe245d8fac',
  'sebastian/exporter' => '2.0.0@ce474bdd1a34744d7ac5d6aad3a46d48d9bac4c4',
  'sebastian/global-state' => '1.1.1@bc37d50fea7d017d3d340f230811c9f1d7280af4',
  'sebastian/object-enumerator' => '2.0.1@1311872ac850040a79c3c058bea3e22d0f09cbb7',
  'sebastian/recursion-context' => '2.0.0@2c3ba150cbec723aa057506e73a8d33bdb286c9a',
  'sebastian/resource-operations' => '1.0.0@ce990bb21759f94aeafd30209e8cfcdfa8bc3f52',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'sensiolabs/security-checker' => 'v5.0.3@46be3f58adac13084497961e10eed9a7fb4d44d1',
  'simplesamlphp/simplesamlphp-test-framework' => 'v0.0.14@d9b90d829ffd1597f0119570b4b1f5b7c91a56e1',
  'squizlabs/php_codesniffer' => '3.5.6@e97627871a7eab2f70e59166072a6b767d5834e0',
  'symfony/console' => 'v3.4.43@afc7189694d2c59546cf24ea606a236fa46a966e',
  'symfony/polyfill-intl-idn' => 'v1.18.1@5dcab1bc7146cf8c1beaa4502a3d9be344334251',
  'symfony/polyfill-intl-normalizer' => 'v1.18.1@37078a8dd4a2a1e9ab0231af7c6cb671b2ed5a7e',
  'symfony/polyfill-php72' => 'v1.18.1@639447d008615574653fb3bc60d1986d7172eaae',
  'symfony/stopwatch' => 'v3.4.43@a7a98f40dcc382a332c3729a6d04b298ffbb8f1f',
  'vimeo/psalm' => '1.1.9@d15cf3b7f50249caf933144c8926c8e69aff3d34',
  'simplesamlphp/simplesamlphp' => '1.18.8.0@',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion($packageName)
    {
        $selfVersion = self::$VERSIONS;

        if (! isset($selfVersion[$packageName])) {
            throw new \OutOfBoundsException(
                'Required package "' . $packageName . '" is not installed: cannot detect its version'
            );
        }

        return $selfVersion[$packageName];
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getShortVersion($packageName)
    {
        return explode('@', static::getVersion($packageName))[0];
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getMajorVersion($packageName)
    {
        return explode('.', static::getShortVersion($packageName))[0];
    }
}
